apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1028"},"creationTimestamp":"2022-01-01T18:54:34Z","generation":1030,"labels":{"app.kubernetes.io/instance":"deployapp","run":"hr-service-dev"},"name":"hr-service-dev","namespace":"default","resourceVersion":"973218341","uid":"26edb062-2ee9-492d-a8e0-1909112d05ff"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"run":"hr-service-dev"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2024-05-08T15:32:12Z"},"creationTimestamp":null,"labels":{"run":"hr-service-dev"}},"spec":{"containers":[{"env":null,"image":"nginx:latest","imagePullPolicy":"Always","name":"hr-service-dev","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{"limits":{"cpu":"1","memory":"2Gi"},"requests":{"cpu":"200m"}},"terminationMessagePath":"/dev/hr-service-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/usr/hr-service-dev/config.properties","name":"config"},{"mountPath":"/etc/hr-service-dev/secrets","name":"secret"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":60,"volumes":[{"configMap":{"defaultMode":420,"name":"hr-service-dev-configmap"},"name":"config"},{"name":"secret","secret":{"defaultMode":420,"secretName":"hr-service-dev-secret"}}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2024-12-04T08:41:52Z","lastUpdateTime":"2024-12-04T08:41:52Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2022-01-01T18:54:34Z","lastUpdateTime":"2024-12-06T11:19:04Z","message":"ReplicaSet \"hr-service-dev-5748ff5c48\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1030,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2024-12-18T13:34:27Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: deployapp
    run: hr-service-dev
  name: hr-service-dev
  namespace: default
  resourceVersion: "180720"
  uid: bbf6ac3c-6c93-4807-aeec-86b069867be2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: hr-service-dev
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-05-08T15:32:12Z"
      creationTimestamp: null
      labels:
        run: hr-service-dev
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: hr-service-dev
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 200m
        terminationMessagePath: /dev/hr-service-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/hr-service-dev/config.properties
          name: config
        - mountPath: /etc/hr-service-dev/secrets
          name: secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - configMap:
          defaultMode: 420
          name: hr-service-dev-configmap
        name: config
      - name: secret
        secret:
          defaultMode: 420
          secretName: hr-service-dev-secret
status:
  conditions:
  - lastTransitionTime: "2024-12-18T13:34:27Z"
    lastUpdateTime: "2024-12-18T13:34:27Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2024-12-18T13:44:28Z"
    lastUpdateTime: "2024-12-18T13:44:28Z"
    message: ReplicaSet "hr-service-dev-695c874cd4" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
